git:
  depth: 1
sudo: false
language: node_js
before_install:
  - sh -c "if [ '$ESLINT_VERSION' = '2' ]; then npm i --save-dev eslint@2; fi"
matrix:
  include:
    - node_js: "0.10"
      env: ESLINT_VERSION=2
    - node_js: "0.12"
      env: ESLINT_VERSION=2
    - node_js: "4"
      env: ESLINT_VERSION=2
    - node_js: "4"
      env: ESLINT_VERSION=3
    - node_js: "5"
      env: ESLINT_VERSION=2
    - node_js: "5"
      env: ESLINT_VERSION=3
    - node_js: "6"
      env: ESLINT_VERSION=2
    - node_js: "6"
      env: ESLINT_VERSION=3
