sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: LINT=true

script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -z "${LINT-}" ]; then npm test ; fi'
